# Generated by Django 3.0.7 on 2020-08-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborator',
            options={'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AddField(
            model_name='note',
            name='category_order',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='top_order',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
