# Generated by Django 3.0.7 on 2020-08-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200816_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='order',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
